name: Bug Report
description: Report a bug in Picksy
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: input
    attributes:
      label: Device / OS
      placeholder: "e.g. Pixel 7 / Android 14"
  - type: input
    attributes:
      label: App version
      placeholder: "e.g. 1.0.0"
