name: Feature Request
description: Suggest a new feature for Picksy
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What do you want?
      description: Describe the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it useful?
      description: What problem does it solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any examples?
      placeholder: "Similar apps / screenshots / links"
